# Generated by Django 2.0.2 on 2018-03-08 09:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180304_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 8, 9, 25, 42, 543709, tzinfo=utc)),
        ),
    ]
