# Generated by Django 2.0.2 on 2018-03-09 17:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180308_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 9, 17, 4, 48, 408308, tzinfo=utc)),
        ),
    ]
