# Generated by Django 2.0.2 on 2018-04-16 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180409_1049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleEvent',
        ),
        migrations.DeleteModel(
            name='SimpleEvent2',
        ),
    ]
