# Generated by Django 2.0.2 on 2018-04-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20180427_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstarred',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='starred',
            name='event',
        ),
        migrations.AddField(
            model_name='starred',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', to='events.Event'),
        ),
        migrations.DeleteModel(
            name='UserStarred',
        ),
    ]
