# Generated by Django 2.0.2 on 2018-04-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20180427_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starred',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='events.Event'),
        ),
    ]
